
ALTER TABLE journals ALTER COLUMN id DROP DEFAULT;
ALTER TABLE traces ALTER COLUMN id DROP DEFAULT;
ALTER TABLE landscape_analyses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE landmarks ALTER COLUMN id DROP DEFAULT;
ALTER TABLE trace_mirrors ALTER COLUMN id DROP DEFAULT;
ALTER TABLE elements ALTER COLUMN id DROP DEFAULT;
ALTER TABLE "references" ALTER COLUMN id DROP DEFAULT;
ALTER TABLE lenses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE posts ALTER COLUMN id DROP DEFAULT;

